language: csharp
solution: GraphCollection.sln
install:
  - nuget restore GraphCollection.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GraphCollection.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./GraphCollection.Tests/bin/Release/GraphCollection.Tests.dll
